### PR TITLE
Spectrum extension for VL.Audio

### PR DESCRIPTION
**Pull request by chkw-rks**
Added an extension to visualize the spectrum of the current audio input for quick analysis. Please let me know, if there are suggestions for improvements!

spectrum_20231002175925

### CODE REVIEW

**Comment by chkw-rks** [comment]
I think that is good enough now to be reviewed.

**Comment by joreg** [comment]
good stuff!

two things though: 
- please remove the reference to VL.WinformsUtils
- the windows behavior should be identical to the Configuration extension: there is a minimum size, but no maximum. maximization is allowed and the spectrum view should size accordingly while the UI elements are docked to the bottom

**Comment by chkw-rks** [comment]
Implemented the feedback!

**Comment by chkw-rks** [comment]
There is now a conflict in VL.Audio, although I thought I have taken care of not touching it... apparently it happened. 
But I think the changes in VL.Audio can be savely ignored.

**Comment by joreg** [comment]
thanks. this is now included in latest previews!

**Pull request merged**
